# Generated by Django 2.2.2 on 2019-06-21 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 6, 21, 22, 45, 40, 446190))),
                ('connection_status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], max_length=15)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='Reading.Meter')),
            ],
            options={
                'ordering': ['sequence_id'],
            },
        ),
    ]
